name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    name: Check quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['pnpm build', 'pnpm lint']

    steps:
      - name: Checkout with sha
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          cache-dependency-path: 'pnpm.lock'
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: pnpm install

      - name: CI commands
        run: ${{ matrix.command }}
